### ISSUE TITLE
Stan LDA benchmark is slow

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/TuringExamples#30]
@SteveBronder the Stan LDA model on master now seems to be really slow, about 7x slower than the Turing counterpart on my machine. This is slower than model that was there before #25. Can someone else reproduce this? If so, is it fine to revert the LDA changes in #25?

**Comment by SteveBronder** [comment]
Oh sorry I thought I reverted that, yeah it's fine to revert those changes

**Comment by mohamed82008** [comment]
👍 cool!

**Comment by mohamed82008** [comment]
Done.
